version: '3.9'

services:
  minio:
    container_name: minio
    image: quay.io/minio/minio:latest
    volumes:
      - minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: 'admin'
      MINIO_ROOT_PASSWORD: 'minio_pass'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data
    networks:
      - modestymart


  modestymart_service:
    container_name: modestymart_service
    build: .
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - modestymart

  migrate:
    image: migrate/migrate
    networks:
      - modestymart
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations", 
      "-database", "postgres://postgres:1234@postgres-db:5432/modestymart?sslmode=disable", 
      "up"
    ]
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    container_name: modestymart
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
      POSTGRES_DB: modestymart
    volumes:
      - db:/project-database/project-memory
    ports:
      - "5434:5434"
    networks:
      - modestymart
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d modestymart -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: "redis:latest"
    container_name: redis_auth
    ports:
      - "6377:6379"
    networks:
      - modestymart

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22018:20181
    networks:
      - modestymart

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29097:29092
    networks:
      - modestymart
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  modestymart:
    driver: bridge
    external: true

volumes:
  minio:
  db: