// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: modestyMart_submodule/cart.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCartReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CartNumber string  `protobuf:"bytes,1,opt,name=cart_number,json=cartNumber,proto3" json:"cart_number,omitempty"`
	CartName   string  `protobuf:"bytes,2,opt,name=cart_name,json=cartName,proto3" json:"cart_name,omitempty"`
	Amount     float32 `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	UserId     string  `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *CreateCartReq) Reset() {
	*x = CreateCartReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modestyMart_submodule_cart_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCartReq) ProtoMessage() {}

func (x *CreateCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_modestyMart_submodule_cart_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCartReq.ProtoReflect.Descriptor instead.
func (*CreateCartReq) Descriptor() ([]byte, []int) {
	return file_modestyMart_submodule_cart_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCartReq) GetCartNumber() string {
	if x != nil {
		return x.CartNumber
	}
	return ""
}

func (x *CreateCartReq) GetCartName() string {
	if x != nil {
		return x.CartName
	}
	return ""
}

func (x *CreateCartReq) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateCartReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Cart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CartNumber string   `protobuf:"bytes,2,opt,name=cart_number,json=cartNumber,proto3" json:"cart_number,omitempty"`
	CartName   string   `protobuf:"bytes,3,opt,name=cart_name,json=cartName,proto3" json:"cart_name,omitempty"`
	Amount     float32  `protobuf:"fixed32,4,opt,name=amount,proto3" json:"amount,omitempty"`
	User       *UserRes `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	CreatedAt  string   `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Cart) Reset() {
	*x = Cart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modestyMart_submodule_cart_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cart) ProtoMessage() {}

func (x *Cart) ProtoReflect() protoreflect.Message {
	mi := &file_modestyMart_submodule_cart_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cart.ProtoReflect.Descriptor instead.
func (*Cart) Descriptor() ([]byte, []int) {
	return file_modestyMart_submodule_cart_proto_rawDescGZIP(), []int{1}
}

func (x *Cart) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cart) GetCartNumber() string {
	if x != nil {
		return x.CartNumber
	}
	return ""
}

func (x *Cart) GetCartName() string {
	if x != nil {
		return x.CartName
	}
	return ""
}

func (x *Cart) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Cart) GetUser() *UserRes {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Cart) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListAllCartReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination *Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	CartName   string      `protobuf:"bytes,2,opt,name=cart_name,json=cartName,proto3" json:"cart_name,omitempty"`
}

func (x *ListAllCartReq) Reset() {
	*x = ListAllCartReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modestyMart_submodule_cart_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAllCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllCartReq) ProtoMessage() {}

func (x *ListAllCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_modestyMart_submodule_cart_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllCartReq.ProtoReflect.Descriptor instead.
func (*ListAllCartReq) Descriptor() ([]byte, []int) {
	return file_modestyMart_submodule_cart_proto_rawDescGZIP(), []int{2}
}

func (x *ListAllCartReq) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListAllCartReq) GetCartName() string {
	if x != nil {
		return x.CartName
	}
	return ""
}

type ListAllCartRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Carts []*Cart `protobuf:"bytes,1,rep,name=carts,proto3" json:"carts,omitempty"`
	Count int32   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ListAllCartRes) Reset() {
	*x = ListAllCartRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modestyMart_submodule_cart_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAllCartRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllCartRes) ProtoMessage() {}

func (x *ListAllCartRes) ProtoReflect() protoreflect.Message {
	mi := &file_modestyMart_submodule_cart_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllCartRes.ProtoReflect.Descriptor instead.
func (*ListAllCartRes) Descriptor() ([]byte, []int) {
	return file_modestyMart_submodule_cart_proto_rawDescGZIP(), []int{3}
}

func (x *ListAllCartRes) GetCarts() []*Cart {
	if x != nil {
		return x.Carts
	}
	return nil
}

func (x *ListAllCartRes) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_modestyMart_submodule_cart_proto protoreflect.FileDescriptor

var file_modestyMart_submodule_cart_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6d, 0x6f, 0x64, 0x65, 0x73, 0x74, 0x79, 0x4d, 0x61, 0x72, 0x74, 0x5f, 0x73, 0x75,
	0x62, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x22, 0x6d, 0x6f, 0x64, 0x65, 0x73,
	0x74, 0x79, 0x4d, 0x61, 0x72, 0x74, 0x5f, 0x73, 0x75, 0x62, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x6d,
	0x6f, 0x64, 0x65, 0x73, 0x74, 0x79, 0x4d, 0x61, 0x72, 0x74, 0x5f, 0x73, 0x75, 0x62, 0x6d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x7e, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x72, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x72, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0xaf, 0x01, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x72, 0x74,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63,
	0x61, 0x72, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x72,
	0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61,
	0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x22, 0x60, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x31, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x74, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x72, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x49, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x61, 0x72,
	0x74, 0x52, 0x05, 0x63, 0x61, 0x72, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0xa3,
	0x01, 0x0a, 0x0b, 0x43, 0x61, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2f,
	0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x74, 0x12, 0x14, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12,
	0x3b, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x61, 0x72, 0x74, 0x12, 0x15,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x07,
	0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x74, 0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x61, 0x72, 0x74, 0x42, 0x17, 0x5a, 0x15, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_modestyMart_submodule_cart_proto_rawDescOnce sync.Once
	file_modestyMart_submodule_cart_proto_rawDescData = file_modestyMart_submodule_cart_proto_rawDesc
)

func file_modestyMart_submodule_cart_proto_rawDescGZIP() []byte {
	file_modestyMart_submodule_cart_proto_rawDescOnce.Do(func() {
		file_modestyMart_submodule_cart_proto_rawDescData = protoimpl.X.CompressGZIP(file_modestyMart_submodule_cart_proto_rawDescData)
	})
	return file_modestyMart_submodule_cart_proto_rawDescData
}

var file_modestyMart_submodule_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_modestyMart_submodule_cart_proto_goTypes = []any{
	(*CreateCartReq)(nil),  // 0: proto.CreateCartReq
	(*Cart)(nil),           // 1: proto.Cart
	(*ListAllCartReq)(nil), // 2: proto.ListAllCartReq
	(*ListAllCartRes)(nil), // 3: proto.ListAllCartRes
	(*UserRes)(nil),        // 4: proto.UserRes
	(*Pagination)(nil),     // 5: proto.Pagination
	(*GetById)(nil),        // 6: proto.GetById
	(*Void)(nil),           // 7: proto.Void
}
var file_modestyMart_submodule_cart_proto_depIdxs = []int32{
	4, // 0: proto.Cart.user:type_name -> proto.UserRes
	5, // 1: proto.ListAllCartReq.pagination:type_name -> proto.Pagination
	1, // 2: proto.ListAllCartRes.carts:type_name -> proto.Cart
	0, // 3: proto.CartService.CreateCart:input_type -> proto.CreateCartReq
	2, // 4: proto.CartService.ListAllCart:input_type -> proto.ListAllCartReq
	6, // 5: proto.CartService.GetCart:input_type -> proto.GetById
	7, // 6: proto.CartService.CreateCart:output_type -> proto.Void
	3, // 7: proto.CartService.ListAllCart:output_type -> proto.ListAllCartRes
	1, // 8: proto.CartService.GetCart:output_type -> proto.Cart
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_modestyMart_submodule_cart_proto_init() }
func file_modestyMart_submodule_cart_proto_init() {
	if File_modestyMart_submodule_cart_proto != nil {
		return
	}
	file_modestyMart_submodule_common_proto_init()
	file_modestyMart_submodule_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_modestyMart_submodule_cart_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateCartReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modestyMart_submodule_cart_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Cart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modestyMart_submodule_cart_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ListAllCartReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modestyMart_submodule_cart_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ListAllCartRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modestyMart_submodule_cart_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modestyMart_submodule_cart_proto_goTypes,
		DependencyIndexes: file_modestyMart_submodule_cart_proto_depIdxs,
		MessageInfos:      file_modestyMart_submodule_cart_proto_msgTypes,
	}.Build()
	File_modestyMart_submodule_cart_proto = out.File
	file_modestyMart_submodule_cart_proto_rawDesc = nil
	file_modestyMart_submodule_cart_proto_goTypes = nil
	file_modestyMart_submodule_cart_proto_depIdxs = nil
}
